=begin
NetRobots API

NetRobots REST API specification, using Swagger format.

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::FireCommand
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FireCommand' do
  before do
    # run before each test
    @instance = SwaggerClient::FireCommand.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FireCommand' do
    it 'should create an instact of FireCommand' do
      @instance.should be_a(SwaggerClient::FireCommand) 
    end
  end
  describe 'test attribute "direction"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "distance"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

