# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class EventScan(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        EventScan - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'event_type': 'float',
            'activation_time': 'float',
            'direction': 'float',
            'semiaperture': 'float',
            'scan_max_distance': 'float',
            'robot': 'RobotInfo',
            'hit_robot': 'RobotInfo'
        }

        self.attribute_map = {
            'event_type': 'eventType',
            'activation_time': 'activationTime',
            'direction': 'direction',
            'semiaperture': 'semiaperture',
            'scan_max_distance': 'scanMaxDistance',
            'robot': 'robot',
            'hit_robot': 'hitRobot'
        }

        self._event_type = None
        self._activation_time = None
        self._direction = None
        self._semiaperture = None
        self._scan_max_distance = None
        self._robot = None
        self._hit_robot = None

    @property
    def event_type(self):
        """
        Gets the event_type of this EventScan.
        tag 3

        :return: The event_type of this EventScan.
        :rtype: float
        """
        return self._event_type

    @event_type.setter
    def event_type(self, event_type):
        """
        Sets the event_type of this EventScan.
        tag 3

        :param event_type: The event_type of this EventScan.
        :type: float
        """
        self._event_type = event_type

    @property
    def activation_time(self):
        """
        Gets the activation_time of this EventScan.
        When the event become active.

        :return: The activation_time of this EventScan.
        :rtype: float
        """
        return self._activation_time

    @activation_time.setter
    def activation_time(self, activation_time):
        """
        Sets the activation_time of this EventScan.
        When the event become active.

        :param activation_time: The activation_time of this EventScan.
        :type: float
        """
        self._activation_time = activation_time

    @property
    def direction(self):
        """
        Gets the direction of this EventScan.
        Direction expressed in degrees. 0 degree is EAST, 90 degree is NORTH, 180 degree is WEST, 270 degree is SOUTH

        :return: The direction of this EventScan.
        :rtype: float
        """
        return self._direction

    @direction.setter
    def direction(self, direction):
        """
        Sets the direction of this EventScan.
        Direction expressed in degrees. 0 degree is EAST, 90 degree is NORTH, 180 degree is WEST, 270 degree is SOUTH

        :param direction: The direction of this EventScan.
        :type: float
        """
        self._direction = direction

    @property
    def semiaperture(self):
        """
        Gets the semiaperture of this EventScan.
        The aperture angle, in degree, divided by 2.

        :return: The semiaperture of this EventScan.
        :rtype: float
        """
        return self._semiaperture

    @semiaperture.setter
    def semiaperture(self, semiaperture):
        """
        Sets the semiaperture of this EventScan.
        The aperture angle, in degree, divided by 2.

        :param semiaperture: The semiaperture of this EventScan.
        :type: float
        """
        self._semiaperture = semiaperture

    @property
    def scan_max_distance(self):
        """
        Gets the scan_max_distance of this EventScan.
        The maximum possible distance of the scan.

        :return: The scan_max_distance of this EventScan.
        :rtype: float
        """
        return self._scan_max_distance

    @scan_max_distance.setter
    def scan_max_distance(self, scan_max_distance):
        """
        Sets the scan_max_distance of this EventScan.
        The maximum possible distance of the scan.

        :param scan_max_distance: The scan_max_distance of this EventScan.
        :type: float
        """
        self._scan_max_distance = scan_max_distance

    @property
    def robot(self):
        """
        Gets the robot of this EventScan.


        :return: The robot of this EventScan.
        :rtype: RobotInfo
        """
        return self._robot

    @robot.setter
    def robot(self, robot):
        """
        Sets the robot of this EventScan.


        :param robot: The robot of this EventScan.
        :type: RobotInfo
        """
        self._robot = robot

    @property
    def hit_robot(self):
        """
        Gets the hit_robot of this EventScan.


        :return: The hit_robot of this EventScan.
        :rtype: RobotInfo
        """
        return self._hit_robot

    @hit_robot.setter
    def hit_robot(self, hit_robot):
        """
        Sets the hit_robot of this EventScan.


        :param hit_robot: The hit_robot of this EventScan.
        :type: RobotInfo
        """
        self._hit_robot = hit_robot

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

