# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class RobotConfiguration(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        RobotConfiguration - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'name': 'str',
            'max_hit_points': 'RobotHealth',
            'max_speed': 'Speed',
            'max_acceleration': 'Speed',
            'max_decelleration': 'Speed',
            'max_sterling_speed': 'Speed',
            'max_scan_distance': 'Distance',
            'max_fire_distance': 'Distance',
            'bullet_speed': 'Speed',
            'bullet_damage': 'RobotHealth',
            'fire_reloading_time': 'float'
        }

        self.attribute_map = {
            'name': 'name',
            'max_hit_points': 'maxHitPoints',
            'max_speed': 'maxSpeed',
            'max_acceleration': 'maxAcceleration',
            'max_decelleration': 'maxDecelleration',
            'max_sterling_speed': 'maxSterlingSpeed',
            'max_scan_distance': 'maxScanDistance',
            'max_fire_distance': 'maxFireDistance',
            'bullet_speed': 'bulletSpeed',
            'bullet_damage': 'bulletDamage',
            'fire_reloading_time': 'fireReloadingTime'
        }

        self._name = None
        self._max_hit_points = None
        self._max_speed = None
        self._max_acceleration = None
        self._max_decelleration = None
        self._max_sterling_speed = None
        self._max_scan_distance = None
        self._max_fire_distance = None
        self._bullet_speed = None
        self._bullet_damage = None
        self._fire_reloading_time = None

    @property
    def name(self):
        """
        Gets the name of this RobotConfiguration.


        :return: The name of this RobotConfiguration.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this RobotConfiguration.


        :param name: The name of this RobotConfiguration.
        :type: str
        """
        self._name = name

    @property
    def max_hit_points(self):
        """
        Gets the max_hit_points of this RobotConfiguration.


        :return: The max_hit_points of this RobotConfiguration.
        :rtype: RobotHealth
        """
        return self._max_hit_points

    @max_hit_points.setter
    def max_hit_points(self, max_hit_points):
        """
        Sets the max_hit_points of this RobotConfiguration.


        :param max_hit_points: The max_hit_points of this RobotConfiguration.
        :type: RobotHealth
        """
        self._max_hit_points = max_hit_points

    @property
    def max_speed(self):
        """
        Gets the max_speed of this RobotConfiguration.


        :return: The max_speed of this RobotConfiguration.
        :rtype: Speed
        """
        return self._max_speed

    @max_speed.setter
    def max_speed(self, max_speed):
        """
        Sets the max_speed of this RobotConfiguration.


        :param max_speed: The max_speed of this RobotConfiguration.
        :type: Speed
        """
        self._max_speed = max_speed

    @property
    def max_acceleration(self):
        """
        Gets the max_acceleration of this RobotConfiguration.


        :return: The max_acceleration of this RobotConfiguration.
        :rtype: Speed
        """
        return self._max_acceleration

    @max_acceleration.setter
    def max_acceleration(self, max_acceleration):
        """
        Sets the max_acceleration of this RobotConfiguration.


        :param max_acceleration: The max_acceleration of this RobotConfiguration.
        :type: Speed
        """
        self._max_acceleration = max_acceleration

    @property
    def max_decelleration(self):
        """
        Gets the max_decelleration of this RobotConfiguration.


        :return: The max_decelleration of this RobotConfiguration.
        :rtype: Speed
        """
        return self._max_decelleration

    @max_decelleration.setter
    def max_decelleration(self, max_decelleration):
        """
        Sets the max_decelleration of this RobotConfiguration.


        :param max_decelleration: The max_decelleration of this RobotConfiguration.
        :type: Speed
        """
        self._max_decelleration = max_decelleration

    @property
    def max_sterling_speed(self):
        """
        Gets the max_sterling_speed of this RobotConfiguration.


        :return: The max_sterling_speed of this RobotConfiguration.
        :rtype: Speed
        """
        return self._max_sterling_speed

    @max_sterling_speed.setter
    def max_sterling_speed(self, max_sterling_speed):
        """
        Sets the max_sterling_speed of this RobotConfiguration.


        :param max_sterling_speed: The max_sterling_speed of this RobotConfiguration.
        :type: Speed
        """
        self._max_sterling_speed = max_sterling_speed

    @property
    def max_scan_distance(self):
        """
        Gets the max_scan_distance of this RobotConfiguration.


        :return: The max_scan_distance of this RobotConfiguration.
        :rtype: Distance
        """
        return self._max_scan_distance

    @max_scan_distance.setter
    def max_scan_distance(self, max_scan_distance):
        """
        Sets the max_scan_distance of this RobotConfiguration.


        :param max_scan_distance: The max_scan_distance of this RobotConfiguration.
        :type: Distance
        """
        self._max_scan_distance = max_scan_distance

    @property
    def max_fire_distance(self):
        """
        Gets the max_fire_distance of this RobotConfiguration.


        :return: The max_fire_distance of this RobotConfiguration.
        :rtype: Distance
        """
        return self._max_fire_distance

    @max_fire_distance.setter
    def max_fire_distance(self, max_fire_distance):
        """
        Sets the max_fire_distance of this RobotConfiguration.


        :param max_fire_distance: The max_fire_distance of this RobotConfiguration.
        :type: Distance
        """
        self._max_fire_distance = max_fire_distance

    @property
    def bullet_speed(self):
        """
        Gets the bullet_speed of this RobotConfiguration.


        :return: The bullet_speed of this RobotConfiguration.
        :rtype: Speed
        """
        return self._bullet_speed

    @bullet_speed.setter
    def bullet_speed(self, bullet_speed):
        """
        Sets the bullet_speed of this RobotConfiguration.


        :param bullet_speed: The bullet_speed of this RobotConfiguration.
        :type: Speed
        """
        self._bullet_speed = bullet_speed

    @property
    def bullet_damage(self):
        """
        Gets the bullet_damage of this RobotConfiguration.


        :return: The bullet_damage of this RobotConfiguration.
        :rtype: RobotHealth
        """
        return self._bullet_damage

    @bullet_damage.setter
    def bullet_damage(self, bullet_damage):
        """
        Sets the bullet_damage of this RobotConfiguration.


        :param bullet_damage: The bullet_damage of this RobotConfiguration.
        :type: RobotHealth
        """
        self._bullet_damage = bullet_damage

    @property
    def fire_reloading_time(self):
        """
        Gets the fire_reloading_time of this RobotConfiguration.


        :return: The fire_reloading_time of this RobotConfiguration.
        :rtype: float
        """
        return self._fire_reloading_time

    @fire_reloading_time.setter
    def fire_reloading_time(self, fire_reloading_time):
        """
        Sets the fire_reloading_time of this RobotConfiguration.


        :param fire_reloading_time: The fire_reloading_time of this RobotConfiguration.
        :type: float
        """
        self._fire_reloading_time = fire_reloading_time

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

