=begin
NetRobots API

NetRobots API

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::ScanStatus
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ScanStatus' do
  before do
    # run before each test
    @instance = SwaggerClient::ScanStatus.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ScanStatus' do
    it 'should create an instact of ScanStatus' do
      @instance.should be_a(SwaggerClient::ScanStatus) 
    end
  end
  describe 'test attribute "direction"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "semi_aperture_angle"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "distance"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

