<?php
/**
 * EventScan
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * EventScan Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EventScan extends Event implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'event_type' => 'Number',
        'direction' => 'float',
        'semiaperture' => 'float',
        'scan_max_distance' => 'float',
        'robot' => '\Swagger\Client\Model\RobotInfo',
        'hit_robot' => '\Swagger\Client\Model\RobotInfo'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes + parent::swaggerTypes();
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'event_type' => 'eventType',
        'direction' => 'direction',
        'semiaperture' => 'semiaperture',
        'scan_max_distance' => 'scanMaxDistance',
        'robot' => 'robot',
        'hit_robot' => 'hitRobot'
    );
  
    static function attributeMap() {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'event_type' => 'setEventType',
        'direction' => 'setDirection',
        'semiaperture' => 'setSemiaperture',
        'scan_max_distance' => 'setScanMaxDistance',
        'robot' => 'setRobot',
        'hit_robot' => 'setHitRobot'
    );
  
    static function setters() {
        return parent::setters() + self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'event_type' => 'getEventType',
        'direction' => 'getDirection',
        'semiaperture' => 'getSemiaperture',
        'scan_max_distance' => 'getScanMaxDistance',
        'robot' => 'getRobot',
        'hit_robot' => 'getHitRobot'
    );
  
    static function getters() {
        return parent::getters() + self::$getters;
    }

    
    /**
      * $event_type tag 3
      * @var Number
      */
    protected $event_type;
    
    /**
      * $direction Direction expressed in degrees. 0 degree is EAST, 90 degree is NORTH, 180 degree is WEST, 270 degree is SOUTH
      * @var float
      */
    protected $direction;
    
    /**
      * $semiaperture The aperture angle, in degree, divided by 2.
      * @var float
      */
    protected $semiaperture;
    
    /**
      * $scan_max_distance The maximum possible distance of the scan.
      * @var float
      */
    protected $scan_max_distance;
    
    /**
      * $robot 
      * @var \Swagger\Client\Model\RobotInfo
      */
    protected $robot;
    
    /**
      * $hit_robot 
      * @var \Swagger\Client\Model\RobotInfo
      */
    protected $hit_robot;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        parent::__construct($data);
        if ($data != null) {
            $this->event_type = $data["event_type"];
            $this->direction = $data["direction"];
            $this->semiaperture = $data["semiaperture"];
            $this->scan_max_distance = $data["scan_max_distance"];
            $this->robot = $data["robot"];
            $this->hit_robot = $data["hit_robot"];
        }
    }
    
    /**
     * Gets event_type
     * @return Number
     */
    public function getEventType()
    {
        return $this->event_type;
    }
  
    /**
     * Sets event_type
     * @param Number $event_type tag 3
     * @return $this
     */
    public function setEventType($event_type)
    {
        
        $this->event_type = $event_type;
        return $this;
    }
    
    /**
     * Gets direction
     * @return float
     */
    public function getDirection()
    {
        return $this->direction;
    }
  
    /**
     * Sets direction
     * @param float $direction Direction expressed in degrees. 0 degree is EAST, 90 degree is NORTH, 180 degree is WEST, 270 degree is SOUTH
     * @return $this
     */
    public function setDirection($direction)
    {
        
        $this->direction = $direction;
        return $this;
    }
    
    /**
     * Gets semiaperture
     * @return float
     */
    public function getSemiaperture()
    {
        return $this->semiaperture;
    }
  
    /**
     * Sets semiaperture
     * @param float $semiaperture The aperture angle, in degree, divided by 2.
     * @return $this
     */
    public function setSemiaperture($semiaperture)
    {
        
        $this->semiaperture = $semiaperture;
        return $this;
    }
    
    /**
     * Gets scan_max_distance
     * @return float
     */
    public function getScanMaxDistance()
    {
        return $this->scan_max_distance;
    }
  
    /**
     * Sets scan_max_distance
     * @param float $scan_max_distance The maximum possible distance of the scan.
     * @return $this
     */
    public function setScanMaxDistance($scan_max_distance)
    {
        
        $this->scan_max_distance = $scan_max_distance;
        return $this;
    }
    
    /**
     * Gets robot
     * @return \Swagger\Client\Model\RobotInfo
     */
    public function getRobot()
    {
        return $this->robot;
    }
  
    /**
     * Sets robot
     * @param \Swagger\Client\Model\RobotInfo $robot 
     * @return $this
     */
    public function setRobot($robot)
    {
        
        $this->robot = $robot;
        return $this;
    }
    
    /**
     * Gets hit_robot
     * @return \Swagger\Client\Model\RobotInfo
     */
    public function getHitRobot()
    {
        return $this->hit_robot;
    }
  
    /**
     * Sets hit_robot
     * @param \Swagger\Client\Model\RobotInfo $hit_robot 
     * @return $this
     */
    public function setHitRobot($hit_robot)
    {
        
        $this->hit_robot = $hit_robot;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
