=begin
NetRobots API

NetRobots REST API specification, using Swagger format.

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::DefaultApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @instance = SwaggerClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instact of DefaultApi' do
      @instance.should be_a(SwaggerClient::DefaultApi)
    end
  end

  # unit tests for robot_action_post
  # 
  # send an action to a robot. The server will answer after the simulation turn is completed, and it will return the token for the next simulation turn.
  # @param command 
  # @param [Hash] opts the optional parameters
  # @return [RobotStatus]
  describe 'robot_action_post test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for robot_create_post
  # 
  # Create a new robot.
  # @param configuration 
  # @param [Hash] opts the optional parameters
  # @return [RobotStatus]
  describe 'robot_create_post test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for robot_remove_post
  # 
  # Remove a robot.
  # @param remove 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'robot_remove_post test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
