<?php
/**
 * ScanStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * ScanStatus Class Doc Comment
 *
 * @category    Class
 * @description The result of last scan command.
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScanStatus implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'direction' => 'float',
        'semi_aperture_angle' => 'float',
        'distance' => 'float'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'direction' => 'direction',
        'semi_aperture_angle' => 'semiApertureAngle',
        'distance' => 'distance'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'direction' => 'setDirection',
        'semi_aperture_angle' => 'setSemiApertureAngle',
        'distance' => 'setDistance'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'direction' => 'getDirection',
        'semi_aperture_angle' => 'getSemiApertureAngle',
        'distance' => 'getDistance'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $direction Direction expressed in degrees. 0 degree is EAST, 90 degree is NORTH, 180 degree is WEST, 279 degree is SOUTH
      * @var float
      */
    protected $direction;
    
    /**
      * $semi_aperture_angle The aperture angle, in degree, divided by 2.
      * @var float
      */
    protected $semi_aperture_angle;
    
    /**
      * $distance 
      * @var float
      */
    protected $distance;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->direction = $data["direction"];
            $this->semi_aperture_angle = $data["semi_aperture_angle"];
            $this->distance = $data["distance"];
        }
    }
    
    /**
     * Gets direction
     * @return float
     */
    public function getDirection()
    {
        return $this->direction;
    }
  
    /**
     * Sets direction
     * @param float $direction Direction expressed in degrees. 0 degree is EAST, 90 degree is NORTH, 180 degree is WEST, 279 degree is SOUTH
     * @return $this
     */
    public function setDirection($direction)
    {
        
        $this->direction = $direction;
        return $this;
    }
    
    /**
     * Gets semi_aperture_angle
     * @return float
     */
    public function getSemiApertureAngle()
    {
        return $this->semi_aperture_angle;
    }
  
    /**
     * Sets semi_aperture_angle
     * @param float $semi_aperture_angle The aperture angle, in degree, divided by 2.
     * @return $this
     */
    public function setSemiApertureAngle($semi_aperture_angle)
    {
        
        $this->semi_aperture_angle = $semi_aperture_angle;
        return $this;
    }
    
    /**
     * Gets distance
     * @return float
     */
    public function getDistance()
    {
        return $this->distance;
    }
  
    /**
     * Sets distance
     * @param float $distance 
     * @return $this
     */
    public function setDistance($distance)
    {
        
        $this->distance = $distance;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
