# coding: utf-8

"""
DefaultApi.py
Copyright 2016 SmartBear Software

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""

from __future__ import absolute_import

import sys
import os

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class DefaultApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def robot_action_post(self, command, **kwargs):
        """
        
        send an action to a robot. The server will answer after the simulation turn is completed, and it will return the token for the next simulation turn.

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.robot_action_post(command, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param RobotCommand command:  (required)
        :return: RobotStatus
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['command']
        all_params.append('callback')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method robot_action_post" % key
                )
            params[key] = val
        del params['kwargs']

        # verify the required parameter 'command' is set
        if ('command' not in params) or (params['command'] is None):
            raise ValueError("Missing the required parameter `command` when calling `robot_action_post`")

        resource_path = '/robot-action'.replace('{format}', 'json')
        path_params = {}

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'command' in params:
            body_params = params['command']

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, 'POST',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='RobotStatus',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'))
        return response

    def robot_create_post(self, configuration, **kwargs):
        """
        
        Create a new robot.

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.robot_create_post(configuration, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param RobotConfiguration configuration:  (required)
        :return: RobotStatus
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['configuration']
        all_params.append('callback')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method robot_create_post" % key
                )
            params[key] = val
        del params['kwargs']

        # verify the required parameter 'configuration' is set
        if ('configuration' not in params) or (params['configuration'] is None):
            raise ValueError("Missing the required parameter `configuration` when calling `robot_create_post`")

        resource_path = '/robot-create'.replace('{format}', 'json')
        path_params = {}

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'configuration' in params:
            body_params = params['configuration']

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, 'POST',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='RobotStatus',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'))
        return response

    def robot_remove_post(self, remove, **kwargs):
        """
        
        Remove a robot.

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.robot_remove_post(remove, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param RemoveCommand remove:  (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['remove']
        all_params.append('callback')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method robot_remove_post" % key
                )
            params[key] = val
        del params['kwargs']

        # verify the required parameter 'remove' is set
        if ('remove' not in params) or (params['remove'] is None):
            raise ValueError("Missing the required parameter `remove` when calling `robot_remove_post`")

        resource_path = '/robot-remove'.replace('{format}', 'json')
        path_params = {}

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'remove' in params:
            body_params = params['remove']

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, 'POST',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type=None,
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'))
        return response
