=begin
NetRobots API

NetRobots REST API specification, using Swagger format.

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

module SwaggerClient
  VERSION = "1.0.0"
end
